version: '3'
services:
   frontend:
     build: ./frontend
     ports:
       - "3000:3000"
     volumes:
       - ./frontend:/app
       - /app/node_modules


# 로컬 테스트 때 주석 해제
  # openvidu:
  #   image: openvidu/openvidu-dev:2.28.0
  #   container_name: avocado_openvidu
  #   ports:
  #     - "4443:4443"
  #   environment:
  #     - OPENVIDU_SECRET=ssafy

# volumes:
#   mysql_data:
